const filterTableData = (array, filters) => {
  console.log(filters);

  let filteredArray = array;

  if (filters.User.value) {
    filteredArray = filteredArray.filter((summarizerData) =>
      summarizerData.User.includes(filters.User.value)
    );
  }

  if (filters.DocumentId.value) {
    filteredArray = filteredArray.filter((summarizer) =>
      summarizer.DocumentId.includes(filters.DocumentId.value)
    );
  }
  if (filters.Notes.value) {
    filteredArray = filteredArray.filter((summarizer) =>
      summarizer.Notes.includes(filters.Notes.value)
    );
  }

  return filteredArray;
};

const sortByProperty = (array, property, direction = 1) => {
  // Check if direction is 'asc' or 'desc'
  const sortOrder = direction;

  // Sorting the array based on the specified property and direction
  return array.sort((a, b) => {
    // Compare the values of the specified property
    const valueA = a[property];
    const valueB = b[property];

    if (valueA < valueB) return -1 * sortOrder;
    if (valueA > valueB) return 1 * sortOrder;
    return 0;
  });
};

const skipAndTake = (array, skipCount, takeCount) =>
  array.slice(skipCount, skipCount + takeCount);

const SummarizerService = {
  getData() {
    return [
      {
        RecId: 1,
        DateTime: "2023-09-06",
        User: "cfortun0",
        DocumentId: "681602688-8",
        Summary: "lacinia erat vestibulum sed",
        Notes: "Skinder",
        inprogress: true,
      },
      {
        RecId: 2,
        DateTime: "2023-09-20",
        User: "nloakes1",
        DocumentId: "443523183-2",
        Summary: "maecenas rhoncus aliquam lacus morbi",
        Notes: "Twitternation",
        inprogress: true,
      },
      {
        RecId: 3,
        DateTime: "2023-12-10",
        User: "ekenneford2",
        DocumentId: "972824131-3",
        Summary: "dis parturient montes nascetur",
        Notes: "Oozz",
      },
      {
        RecId: 4,
        DateTime: "2024-01-06",
        User: "tlesek3",
        DocumentId: "550357660-8",
        Summary: "in sapien iaculis congue vivamus metus",
        Notes: "Brightdog",
      },
      {
        RecId: 5,
        DateTime: "2023-12-19",
        User: "jpoleye4",
        DocumentId: "170160161-3",
        Summary: "volutpat eleifend donec ut dolor morbi",
        Notes: "Gabcube",
      },
      {
        RecId: 6,
        DateTime: "2023-05-31",
        User: "rgrissett5",
        DocumentId: "850025347-9",
        Summary: "ligula sit amet eleifend",
        Notes: "Devpoint",
      },
      {
        RecId: 7,
        DateTime: "2024-01-11",
        User: "hhaslin6",
        DocumentId: "186306048-0",
        Summary: "urna pretium nisl ut volutpat sapien arcu",
        Notes: "Bluejam",
      },
      {
        RecId: 8,
        DateTime: "2023-05-01",
        User: "pmartusov7",
        DocumentId: "892643918-6",
        Summary: "nulla sed accumsan felis ut",
        Notes: "Gabspot",
      },
      {
        RecId: 9,
        DateTime: "2023-11-20",
        User: "mparminter8",
        DocumentId: "148819193-X",
        Summary: "ipsum aliquam non mauris morbi non lectus",
        Notes: "Devbug",
      },
      {
        RecId: 10,
        DateTime: "2023-07-16",
        User: "cwillmott9",
        DocumentId: "482030825-4",
        Summary: "ut erat id mauris vulputate",
        Notes: "Gabspot",
      },
      {
        RecId: 11,
        DateTime: "2023-10-11",
        User: "dcarstairsa",
        DocumentId: "876891379-6",
        Summary: "placerat ante nulla justo aliquam quis",
        Notes: "Zoomcast",
      },
      {
        RecId: 12,
        DateTime: "2023-08-28",
        User: "smullesb",
        DocumentId: "417999504-2",
        Summary: "nulla nunc purus phasellus",
        Notes: "Dynazzy",
      },
      {
        RecId: 13,
        DateTime: "2023-09-27",
        User: "jbaisec",
        DocumentId: "796628069-1",
        Summary: "nec sem duis aliquam",
        Notes: "Twitternation",
      },
      {
        RecId: 14,
        DateTime: "2023-05-20",
        User: "fcollumbelld",
        DocumentId: "229092549-7",
        Summary: "ligula sit amet eleifend pede libero quis",
        Notes: "Aimbo",
      },
      {
        RecId: 15,
        DateTime: "2023-08-17",
        User: "fboxelle",
        DocumentId: "900751918-2",
        Summary: "consectetuer adipiscing elit proin",
        Notes: "Topicblab",
      },
      {
        RecId: 16,
        DateTime: "2023-04-18",
        User: "hjorgensenf",
        DocumentId: "716453346-6",
        Summary: "enim lorem ipsum dolor",
        Notes: "Viva",
      },
      {
        RecId: 17,
        DateTime: "2023-06-06",
        User: "rserrierg",
        DocumentId: "343111280-3",
        Summary: "dis parturient montes nascetur",
        Notes: "Gigazoom",
      },
      {
        RecId: 18,
        DateTime: "2023-07-14",
        User: "sblondellh",
        DocumentId: "584201186-7",
        Summary: "neque aenean auctor gravida sem",
        Notes: "Fliptune",
      },
      {
        RecId: 19,
        DateTime: "2023-04-30",
        User: "sbockmanni",
        DocumentId: "072883808-7",
        Summary: "curae duis faucibus accumsan odio curabitur convallis",
        Notes: "Photojam",
      },
      {
        RecId: 20,
        DateTime: "2023-08-04",
        User: "gdecruzej",
        DocumentId: "943614176-9",
        Summary: "in purus eu magna vulputate luctus",
        Notes: "Eadel",
      },
      {
        RecId: 21,
        DateTime: "2023-08-04",
        User: "wspriggink",
        DocumentId: "233583013-9",
        Summary: "etiam faucibus cursus urna",
        Notes: "Fiveclub",
      },
      {
        RecId: 22,
        DateTime: "2023-03-29",
        User: "tgimsonl",
        DocumentId: "732782768-4",
        Summary: "vestibulum proin eu mi nulla ac",
        Notes: "Realbridge",
      },
      {
        RecId: 23,
        DateTime: "2023-09-13",
        User: "htapem",
        DocumentId: "591110125-4",
        Summary: "sapien urna pretium nisl ut",
        Notes: "Rhyzio",
      },
      {
        RecId: 24,
        DateTime: "2023-11-21",
        User: "sgreenlyn",
        DocumentId: "349083003-2",
        Summary: "vel augue vestibulum ante ipsum",
        Notes: "Yoveo",
      },
      {
        RecId: 25,
        DateTime: "2023-10-06",
        User: "fburdetto",
        DocumentId: "864677902-5",
        Summary: "eget elit sodales scelerisque mauris sit amet",
        Notes: "Aimbu",
      },
      {
        RecId: 26,
        DateTime: "2023-06-22",
        User: "nolufsenp",
        DocumentId: "284436692-9",
        Summary: "sed augue aliquam erat volutpat",
        Notes: "Realblab",
      },
      {
        RecId: 27,
        DateTime: "2023-10-11",
        User: "lzettoiq",
        DocumentId: "292732683-5",
        Summary: "etiam pretium iaculis justo in hac",
        Notes: "Oyoloo",
      },
      {
        RecId: 28,
        DateTime: "2023-08-12",
        User: "hfullalover",
        DocumentId: "158940459-9",
        Summary: "orci eget orci vehicula condimentum curabitur in",
        Notes: "Pixonyx",
      },
      {
        RecId: 29,
        DateTime: "2023-12-12",
        User: "lhanselmanns",
        DocumentId: "872155555-9",
        Summary: "primis in faucibus orci",
        Notes: "Fadeo",
      },
      {
        RecId: 30,
        DateTime: "2023-05-09",
        User: "cwookeyt",
        DocumentId: "529538404-7",
        Summary: "quis turpis eget elit sodales",
        Notes: "Fanoodle",
      },
      {
        RecId: 31,
        DateTime: "2023-11-02",
        User: "rwynrehameu",
        DocumentId: "126606362-5",
        Summary: "duis bibendum morbi non quam nec dui",
        Notes: "Browseblab",
      },
      {
        RecId: 32,
        DateTime: "2023-10-26",
        User: "ffallsv",
        DocumentId: "431167800-2",
        Summary: "iaculis congue vivamus metus arcu",
        Notes: "Thoughtbridge",
      },
      {
        RecId: 33,
        DateTime: "2023-06-28",
        User: "radolphinew",
        DocumentId: "621207526-3",
        Summary: "quis orci nullam molestie",
        Notes: "Lajo",
      },
      {
        RecId: 34,
        DateTime: "2023-06-19",
        User: "ebyshx",
        DocumentId: "562919244-2",
        Summary: "gravida nisi at nibh in",
        Notes: "Devify",
      },
      {
        RecId: 35,
        DateTime: "2023-04-27",
        User: "bwimpeyy",
        DocumentId: "290878704-0",
        Summary: "cras pellentesque volutpat dui maecenas tristique est",
        Notes: "Topiczoom",
      },
      {
        RecId: 36,
        DateTime: "2023-02-27",
        User: "gmunneryz",
        DocumentId: "847058232-1",
        Summary: "convallis nulla neque libero convallis",
        Notes: "Topicstorm",
      },
      {
        RecId: 37,
        DateTime: "2023-03-14",
        User: "tbaly10",
        DocumentId: "835364980-2",
        Summary: "praesent lectus vestibulum quam",
        Notes: "Fanoodle",
      },
      {
        RecId: 38,
        DateTime: "2023-03-08",
        User: "glidell11",
        DocumentId: "489577463-5",
        Summary: "dictumst maecenas ut massa",
        Notes: "Vipe",
      },
      {
        RecId: 39,
        DateTime: "2023-09-01",
        User: "ecromar12",
        DocumentId: "968470137-3",
        Summary: "nulla integer pede justo lacinia eget",
        Notes: "Mudo",
      },
      {
        RecId: 40,
        DateTime: "2023-12-20",
        User: "nliveley13",
        DocumentId: "073545939-8",
        Summary: "in quis justo maecenas rhoncus aliquam",
        Notes: "Jazzy",
      },
      {
        RecId: 41,
        DateTime: "2023-04-23",
        User: "lmarcham14",
        DocumentId: "188778395-4",
        Summary: "quis tortor id nulla ultrices aliquet",
        Notes: "Oyope",
      },
      {
        RecId: 42,
        DateTime: "2023-08-02",
        User: "zbartul15",
        DocumentId: "327114365-X",
        Summary: "dolor quis odio consequat varius",
        Notes: "Tazzy",
      },
      {
        RecId: 43,
        DateTime: "2023-07-15",
        User: "twinsor16",
        DocumentId: "122757691-9",
        Summary: "feugiat et eros vestibulum ac est lacinia",
        Notes: "Dynabox",
      },
      {
        RecId: 44,
        DateTime: "2023-06-18",
        User: "ebroadwood17",
        DocumentId: "198197267-6",
        Summary: "nascetur ridiculus mus etiam vel augue",
        Notes: "Feedmix",
      },
      {
        RecId: 45,
        DateTime: "2023-10-14",
        User: "mmee18",
        DocumentId: "615889229-7",
        Summary: "a suscipit nulla elit ac nulla sed",
        Notes: "Dynava",
      },
      {
        RecId: 46,
        DateTime: "2023-10-15",
        User: "ekasman19",
        DocumentId: "872431631-8",
        Summary: "eleifend quam a odio in hac habitasse",
        Notes: "Quimba",
      },
      {
        RecId: 47,
        DateTime: "2023-09-02",
        User: "adufty1a",
        DocumentId: "091651371-8",
        Summary: "pretium iaculis diam erat",
        Notes: "Demimbu",
      },
      {
        RecId: 48,
        DateTime: "2023-12-23",
        User: "vmidgely1b",
        DocumentId: "892015868-1",
        Summary: "nec dui luctus rutrum nulla tellus",
        Notes: "Brainbox",
      },
      {
        RecId: 49,
        DateTime: "2023-02-11",
        User: "econgrave1c",
        DocumentId: "476336580-0",
        Summary: "sapien non mi integer ac neque",
        Notes: "Realpoint",
      },
      {
        RecId: 50,
        DateTime: "2024-01-12",
        User: "nmatkovic1d",
        DocumentId: "719967526-7",
        Summary: "nam ultrices libero non",
        Notes: "Flashspan",
      },
      {
        RecId: 51,
        DateTime: "2023-03-25",
        User: "jtomasino1e",
        DocumentId: "650847231-3",
        Summary: "nulla ut erat id mauris",
        Notes: "Buzzster",
      },
      {
        RecId: 52,
        DateTime: "2023-07-27",
        User: "hkhalid1f",
        DocumentId: "704887584-4",
        Summary: "leo odio condimentum id luctus nec",
        Notes: "Topicshots",
      },
      {
        RecId: 53,
        DateTime: "2024-01-25",
        User: "lsloegrave1g",
        DocumentId: "412757226-4",
        Summary: "pede morbi porttitor lorem id",
        Notes: "Skinix",
      },
      {
        RecId: 54,
        DateTime: "2023-09-27",
        User: "pbreyt1h",
        DocumentId: "099736333-9",
        Summary: "faucibus orci luctus et",
        Notes: "Nlounge",
      },
      {
        RecId: 55,
        DateTime: "2023-12-26",
        User: "bsproson1i",
        DocumentId: "851203064-X",
        Summary: "et magnis dis parturient montes nascetur ridiculus",
        Notes: "Eamia",
      },
      {
        RecId: 56,
        DateTime: "2023-03-27",
        User: "jlyptrit1j",
        DocumentId: "216409411-5",
        Summary: "consectetuer eget rutrum at lorem integer tincidunt",
        Notes: "Kwideo",
      },
      {
        RecId: 57,
        DateTime: "2023-10-04",
        User: "webbin1k",
        DocumentId: "053923638-1",
        Summary: "elit sodales scelerisque mauris sit amet",
        Notes: "Tazz",
      },
      {
        RecId: 58,
        DateTime: "2023-02-23",
        User: "aharmes1l",
        DocumentId: "364190850-7",
        Summary: "ligula vehicula consequat morbi a ipsum integer",
        Notes: "Oozz",
      },
      {
        RecId: 59,
        DateTime: "2023-12-15",
        User: "lcovotti1m",
        DocumentId: "172371814-9",
        Summary: "nibh quisque id justo sit",
        Notes: "Yodoo",
      },
      {
        RecId: 60,
        DateTime: "2023-07-04",
        User: "cblazejewski1n",
        DocumentId: "074882983-0",
        Summary: "platea dictumst maecenas ut",
        Notes: "Skyble",
      },
      {
        RecId: 61,
        DateTime: "2023-02-20",
        User: "amatuschek1o",
        DocumentId: "526911266-3",
        Summary: "at turpis donec posuere metus",
        Notes: "Kaymbo",
      },
      {
        RecId: 62,
        DateTime: "2023-07-02",
        User: "gcrees1p",
        DocumentId: "627450332-3",
        Summary: "risus dapibus augue vel accumsan tellus",
        Notes: "Yombu",
      },
      {
        RecId: 63,
        DateTime: "2023-04-27",
        User: "jbellocht1q",
        DocumentId: "092032833-4",
        Summary: "dui vel sem sed sagittis",
        Notes: "Thoughtbridge",
      },
      {
        RecId: 64,
        DateTime: "2023-04-23",
        User: "avigurs1r",
        DocumentId: "785576716-9",
        Summary: "sapien quis libero nullam",
        Notes: "Flipstorm",
      },
      {
        RecId: 65,
        DateTime: "2023-12-07",
        User: "blent1s",
        DocumentId: "556608833-3",
        Summary: "a ipsum integer a nibh in",
        Notes: "Aivee",
      },
      {
        RecId: 66,
        DateTime: "2023-03-17",
        User: "fiskov1t",
        DocumentId: "898018938-9",
        Summary: "enim blandit mi in porttitor pede justo",
        Notes: "Yakijo",
      },
      {
        RecId: 67,
        DateTime: "2023-10-17",
        User: "pnickless1u",
        DocumentId: "748385207-0",
        Summary: "nec nisi vulputate nonummy maecenas tincidunt lacus",
        Notes: "Skyndu",
      },
      {
        RecId: 68,
        DateTime: "2024-01-23",
        User: "lfer1v",
        DocumentId: "565717430-5",
        Summary: "nibh ligula nec sem duis",
        Notes: "Oodoo",
      },
      {
        RecId: 69,
        DateTime: "2024-01-30",
        User: "ttoor1w",
        DocumentId: "834674906-6",
        Summary: "morbi non lectus aliquam",
        Notes: "Camimbo",
      },
      {
        RecId: 70,
        DateTime: "2023-04-01",
        User: "emeredyth1x",
        DocumentId: "970079024-X",
        Summary: "neque aenean auctor gravida sem praesent",
        Notes: "Avamba",
      },
      {
        RecId: 71,
        DateTime: "2023-02-11",
        User: "ededam1y",
        DocumentId: "801294593-2",
        Summary: "sed augue aliquam erat volutpat",
        Notes: "Flashpoint",
      },
      {
        RecId: 72,
        DateTime: "2023-12-13",
        User: "hlottrington1z",
        DocumentId: "318983167-X",
        Summary: "neque aenean auctor gravida sem",
        Notes: "Dabfeed",
      },
      {
        RecId: 73,
        DateTime: "2023-07-15",
        User: "spetett20",
        DocumentId: "999355716-1",
        Summary: "potenti in eleifend quam a odio",
        Notes: "Izio",
      },
      {
        RecId: 74,
        DateTime: "2023-10-22",
        User: "hhubatsch21",
        DocumentId: "647007863-X",
        Summary: "nec molestie sed justo pellentesque",
        Notes: "Aimbo",
      },
      {
        RecId: 75,
        DateTime: "2023-03-08",
        User: "sdudman22",
        DocumentId: "260849189-8",
        Summary: "sit amet turpis elementum ligula vehicula consequat",
        Notes: "Vidoo",
      },
      {
        RecId: 76,
        DateTime: "2023-06-28",
        User: "ltorpie23",
        DocumentId: "642928651-7",
        Summary: "ut blandit non interdum in ante",
        Notes: "Cogibox",
      },
      {
        RecId: 77,
        DateTime: "2023-09-16",
        User: "dcommucci24",
        DocumentId: "785307632-0",
        Summary: "odio consequat varius integer",
        Notes: "Twitterlist",
      },
      {
        RecId: 78,
        DateTime: "2023-11-15",
        User: "flitherland25",
        DocumentId: "790903992-1",
        Summary: "cras mi pede malesuada in imperdiet",
        Notes: "Ailane",
      },
      {
        RecId: 79,
        DateTime: "2024-01-11",
        User: "ssuthren26",
        DocumentId: "461954904-5",
        Summary: "cras non velit nec",
        Notes: "Trunyx",
      },
      {
        RecId: 80,
        DateTime: "2023-08-01",
        User: "scardenosa27",
        DocumentId: "316943381-4",
        Summary: "et commodo vulputate justo",
        Notes: "Roodel",
      },
      {
        RecId: 81,
        DateTime: "2024-01-15",
        User: "vkither28",
        DocumentId: "461770490-6",
        Summary: "ipsum primis in faucibus orci",
        Notes: "Realpoint",
      },
      {
        RecId: 82,
        DateTime: "2023-11-16",
        User: "thans29",
        DocumentId: "455340350-1",
        Summary: "lacinia aenean sit amet justo morbi",
        Notes: "Eamia",
      },
      {
        RecId: 83,
        DateTime: "2023-04-06",
        User: "amaccosty2a",
        DocumentId: "241188011-1",
        Summary: "dapibus at diam nam",
        Notes: "Feedfish",
      },
      {
        RecId: 84,
        DateTime: "2023-02-06",
        User: "hseamon2b",
        DocumentId: "486092071-6",
        Summary: "nascetur ridiculus mus vivamus",
        Notes: "Cogidoo",
      },
      {
        RecId: 85,
        DateTime: "2023-04-18",
        User: "bgoulborn2c",
        DocumentId: "527449370-X",
        Summary: "sit amet nulla quisque",
        Notes: "Skivee",
      },
      {
        RecId: 86,
        DateTime: "2023-12-29",
        User: "bclancey2d",
        DocumentId: "448988291-2",
        Summary: "platea dictumst maecenas ut massa quis augue",
        Notes: "Dynabox",
      },
      {
        RecId: 87,
        DateTime: "2023-05-04",
        User: "ccreasy2e",
        DocumentId: "540613362-4",
        Summary: "suspendisse potenti cras in purus eu magna",
        Notes: "Edgeify",
      },
      {
        RecId: 88,
        DateTime: "2024-01-22",
        User: "dplumbley2f",
        DocumentId: "383870865-2",
        Summary: "tempor convallis nulla neque libero convallis eget",
        Notes: "Divavu",
      },
      {
        RecId: 89,
        DateTime: "2023-06-17",
        User: "pmcphillimey2g",
        DocumentId: "006169861-X",
        Summary: "porttitor id consequat in consequat",
        Notes: "Kaymbo",
      },
      {
        RecId: 90,
        DateTime: "2023-05-15",
        User: "pmcqueen2h",
        DocumentId: "161593927-X",
        Summary: "curabitur gravida nisi at nibh",
        Notes: "Tagchat",
      },
      {
        RecId: 91,
        DateTime: "2023-08-08",
        User: "cmacallester2i",
        DocumentId: "972379237-0",
        Summary: "varius nulla facilisi cras non velit",
        Notes: "Tekfly",
      },
      {
        RecId: 92,
        DateTime: "2023-05-16",
        User: "eraitie2j",
        DocumentId: "700532277-0",
        Summary: "tincidunt lacus at velit vivamus",
        Notes: "Eabox",
      },
      {
        RecId: 93,
        DateTime: "2023-03-01",
        User: "hbrabant2k",
        DocumentId: "176998776-2",
        Summary: "primis in faucibus orci",
        Notes: "Mymm",
      },
      {
        RecId: 94,
        DateTime: "2023-04-26",
        User: "hperone2l",
        DocumentId: "237717251-2",
        Summary: "sagittis dui vel nisl duis",
        Notes: "Youfeed",
      },
      {
        RecId: 95,
        DateTime: "2024-01-30",
        User: "rvenditti2m",
        DocumentId: "882280235-7",
        Summary: "eget rutrum at lorem integer tincidunt ante",
        Notes: "Skinte",
      },
      {
        RecId: 96,
        DateTime: "2024-01-25",
        User: "pquarrington2n",
        DocumentId: "945250324-6",
        Summary: "aliquam augue quam sollicitudin",
        Notes: "Mycat",
      },
      {
        RecId: 97,
        DateTime: "2023-08-17",
        User: "arediers2o",
        DocumentId: "350101203-9",
        Summary: "proin interdum mauris non ligula",
        Notes: "Browsecat",
      },
      {
        RecId: 98,
        DateTime: "2023-07-13",
        User: "tavramovic2p",
        DocumentId: "845856130-1",
        Summary: "suscipit nulla elit ac",
        Notes: "Fivespan",
      },
      {
        RecId: 99,
        DateTime: "2023-05-11",
        User: "snattrass2q",
        DocumentId: "423507877-1",
        Summary: "ipsum aliquam non mauris morbi",
        Notes: "Oyonder",
      },
      {
        RecId: 100,
        DateTime: "2023-05-17",
        User: "jjoriot2r",
        DocumentId: "906245445-3",
        Summary: "mattis pulvinar nulla pede",
        Notes: "Zooveo",
      },
    ];
  },
  getFilterAndPaginatedData(sageDataTableRequest) {
    let dummayData = this.getData();

    let filterData = filterTableData(dummayData, sageDataTableRequest.filters);

    const orderedData = sageDataTableRequest.sortField
      ? sortByProperty(
          filterData,
          sageDataTableRequest.sortField,
          sageDataTableRequest.sortOrder
        )
      : filterData;

    return {
      data: skipAndTake(
        orderedData,
        sageDataTableRequest.first,
        sageDataTableRequest.rows
      ),
      totalRecords: filterData.length,
    };
  },
  getSummaryData() {
    return Promise.resolve(this.getData());
  },
};

module.exports = SummarizerService;
